name: "Build the Master's Thesis as PDF"
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - run: nix build

      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: result/index.pdf
