name: Build the Master\'s Thesis as PDF
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install Tex Gyre Pagella
        run: sudo apt-get update && sudo apt-get install -y fonts-texgyre

      - uses: yegor256/latexmk-action@0.4.0
        with:
          cmd: latexmk
          path: .
          packages: >
            koma-script babel-english
            physics mathtools amsmath fontspec booktabs siunitx caption biblatex float
            pgfplots microtype fancyvrb csquotes setspace newunicodechar hyperref
            cleveref multirow bbold unicode-math biblatex-phys xpatch beamerposter
            type1cm changepage lualatex-math
